###########################################################################
#
# If there are new commits on master, while we have a version bump PR open,
# this job automatically comments on the PR, mentioning the new commits,
# so we will not forget to follow-up the changes.
#
###########################################################################

name: Comment on version bump PR

permissions:
  pull-requests: write

on:
  push:
    branches:
      - master

jobs:
  comment-on-version-bump-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Add comment if necessary
        run: |
          PR_NUMBER=$(gh pr list \
                        --repo "${{ github.repository_owner }}/syslog-ng" \
                        --state "open" \
                        --label "version-bump" \
                        | grep -Po "^[0-9]+") \
                    || true

          if [ -z ${PR_NUMBER} ]; then
            echo "No version bump PR is open. Skipping."
          else
            COMMENT="There are new commits (${COMMIT_URL}) on master. Please follow-up any necessary changes."
            gh pr comment --repo "${{ github.repository_owner }}/syslog-ng" "${PR_NUMBER}" --body "${COMMENT}"
          fi
