name: Create Draft release

on:
  pull_request:
    types: [merged]

jobs:
  create-draft-release:
    runs-on: ubuntu-18.04
    steps:
      - name: merged-e
        if: github.event.pull_request.merged
        run: |
          echo MERGED
