name: Upload draft release

on:
  pull_request:
    types: [closed]

jobs:
  create-draft-release:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-candidate')
    steps:
      - name: merged-e
        run: |
          echo ${{ github.event.issue.labels }}
          echo ${{ github.event.issue }}
          echo ${{ github.event }}
          echo ${{ github.event.issue.labels.* }}
          echo ${{ github.event.issue.labels.*.name }}
          echo ${{ join(github.event.issue.labels.*.name, ', ') }}
          echo ${{ contains(github.event.issue.labels.*.name, 'release-candidate') }}
          echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          cat $GITHUB_EVENT_PATH
          echo ${{ github.event.number }}
          echo ${{ github.event.pull_request }}

