name: CI @ devshell

on: [pull_request, push]

jobs:
  just-the-lint:
    runs-on: ubuntu-18.04
    container:
      image: balabit/syslog-ng-devshell:latest
      env:
        CONFIGURE_FLAGS:
          --prefix=/github/home/install/syslog-ng
          --enable-all-modules
          --with-python=${{ matrix.python }}

    strategy:
      matrix:
        python: [2, 3]
        command: ['python-pep8', 'python-pylint']
      fail-fast: false

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v1

      - name: autogen.sh
        run: ./autogen.sh

      - name: configure
        run: |
          mkdir build
          cd build
          ../configure $CONFIGURE_FLAGS

      - name: pylib linters
        working-directory: ./build
        run: |
          make ${{ matrix.command }}
