name: CI @ devshell

on: [pull_request, push]

jobs:
  commits-check:
    runs-on: ubuntu-18.04
    container:
      image: balabit/syslog-ng-devshell:latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Commits check (Pull request)
        if: github.event_name == 'pull_request'
        run: tests/commits/check.sh origin/${{ github.base_ref }}..HEAD

      - name: Commits check (Push)
        if: github.event_name == 'push'
        run: tests/commits/check.sh
