###########################################################################################
#
# This job creates a draft release into GitHub's releases section.
#
# It is automatically started, when a "Release candidate" PR is merged.
# Its progress is commented at the "Release candidate" PR.
#
# The job can also be started manually, if necessary.
#
# When the job is finished, one must visit https://github.com/syslog-ng/syslog-ng/releases,
# double check the generated draft release, and manually release it.
#
###########################################################################################

name: Draft release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_dispatch') ||
        (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'version-bump'))
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JOB_NAME: "**Draft release** job"
      CURRENT_JOB_URL: https://github.com/${{ github.repository_owner }}/syslog-ng/actions/runs/${{ github.run_id }}
      COMMENT_ENDPOINT: repos/${{ github.repository_owner }}/syslog-ng/issues/${{ github.event.number }}/comments
      RELEASES_URL: https://github.com/${{ github.repository_owner }}/syslog-ng/releases
    steps:
      - name: "Comment: job started"
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="${JOB_NAME} started: ${CURRENT_JOB_URL}."

          hub api \
            ${COMMENT_ENDPOINT} \
            --field body="${COMMENT}"

      - name: Checkout syslog-ng source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          . .github/workflows/gh-tools.sh

          VERSION=`cat VERSION`
          RELEASE_TAG=syslog-ng-$VERSION
          RELEASE_NAME=${RELEASE_TAG}
          TARBALL_PATH=dbld/release/${VERSION}/${RELEASE_NAME}.tar.gz

          gh_export VERSION RELEASE_TAG RELEASE_NAME TARBALL_PATH

      - name: "DBLD: release"
        run: |
          ./dbld/rules release VERSION=${VERSION}

      - name: Store release tarball as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: ${{ env.TARBALL_PATH }}
          if-no-files-found: error

      - name: Create draft release
        run: |
          sed "1 i${RELEASE_NAME}\n" NEWS.md > /tmp/message

          hub release create \
            --draft \
            --file /tmp/message \
            --attach ${TARBALL_PATH} \
            ${RELEASE_TAG}

      - name: "Comment: job status"
        if: github.event_name == 'pull_request' && always()
        run: |
          if [ ${{ job.status }} = 'success' ]
          then
            COMMENT="${JOB_NAME} finished successfully. Please check the Releases page: ${RELEASES_URL}"
          else
            COMMENT="${JOB_NAME}: ${{ job.status }}."
          fi

          hub api \
            ${COMMENT_ENDPOINT} \
            --field body="${COMMENT}"

  packages:
    needs: draft-release
    uses: ./.github/workflows/create-and-upload-packages.yml
    with:
      tarball_artifact_name: "tarball"
      pkg_type: "stable"
