name: Index packages in Azure/incoming


on:
  workflow_call:
    inputs:
      pkg-type:
        required: true
        type: string  # stable / nightly
      run-id:
        required: false
        type: string
    secrets:
      config-base64:
        required: true
      gpg-key-base64:
        required: false


defaults:
  run:
    working-directory: packaging/package-indexer


jobs:
  index-packages:
    name: ${{ inputs.pkg-type }}

    runs-on: ubuntu-latest

    env:
      CONFIG_BASE64: ${{ secrets.config-base64 }}
      GPG_KEY_BASE64: ${{ secrets.gpg-key-base64 }}
      DOCKER_IMAGE: package-indexer
      DOCKER_CONTAINER_NAME: package_indexer_container
      VERBOSE_LOG_PATH: index-packages-verbose.log
      CONFIG_PATH: index-packages-config.yml
      GPG_KEY_PATH: syslog_ng_ose_signing_key.priv.asc

    if: github.repository_owner == 'alltilla'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          . "${GITHUB_WORKSPACE}/.github/workflows/gh-tools.sh"

          if [[ -n "${{ inputs.run-id }}" ]]; then
            RUN_ID="${{ inputs.run-id }}"
          else
            RUN_ID="${{ github.run_id }}"
          fi
          gh_export RUN_ID

          echo "${CONFIG_BASE64}" | base64 --decode > "${CONFIG_PATH}"
          echo "${GPG_KEY_BASE64}" | base64 --decode > "${GPG_KEY_PATH}"
          echo -e "\ngpg-key: ${PWD}/${GPG_KEY_PATH}\n" >> "${CONFIG_PATH}"

      - name: Build docker image
        run: |
          docker build -t "${DOCKER_IMAGE}" .

      - name: Start docker container
        run: |
          docker run -v "${PWD}:${PWD}" -w "${PWD}" --detach --name "${DOCKER_CONTAINER_NAME}" -t "${DOCKER_IMAGE}"

      - name: Index packages
        run: |
          docker exec ${DOCKER_CONTAINER_NAME} \
            ./index-packages.py \
              --suite "${{ inputs.pkg-type }}" \
              --config "${CONFIG_PATH}" \
              --run-id "${RUN_ID}" \
              --log-file "${VERBOSE_LOG_PATH}"

      - name: Cleanup
        if: always()
        run:
          rm -f "${CONFIG_PATH}" "${GPG_KEY_PATH}"

      - name: "Artifact: verbose run log"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.VERBOSE_LOG_PATH }}
          path: packaging/package-indexer/${{ env.VERBOSE_LOG_PATH }}
