name: macOS

on:
  pull_request:
  schedule:
    - cron: '00 21 * * *'

jobs:
  general:
    runs-on: macOS-latest
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2
