name: Nightly packages

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'


jobs:
  create-source-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare docker image
        run: ./dbld/rules cache-image-tarball

      - name: Create source tarball
        run: ./dbld/rules pkg-tarball

      - name: Store source tarball as artifact
        uses: actions/upload-artifact@v2
        with:
          name: source-tarball
          path: dbld/build/*.tar.gz

  create-packages:
    needs: create-source-tarball
    uses: ./.github/workflows/create-packages.yml
    with:
      source-tarball-artifact-name: source-tarball
      dbld-image-mode: cache

  upload-packages:
    needs: create-packages
    uses: ./.github/workflows/upload-packages.yml
    with:
      pkg-type: nightly
