name: Nightly packages

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'


jobs:
  tarball:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare docker image
        run: ./dbld/rules cache-image-tarball

      - name: Create tarball
        run: ./dbld/rules pkg-tarball

      - name: Store tarball as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: dbld/build/*.tar.gz

  packages:
    needs: tarball
    uses: ./.github/workflows/create-and-upload-packages.yml
    with:
      tarball_artifact_name: "tarball"
      upload_as: "nightly"
