name: Packages (PR / push)


on:
  pull_request:
  push:


jobs:
  create-source-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare docker image
        run: |
          docker pull alltilla/syslog-ng-devshell-with-grpc:latest
          docker tag alltilla/syslog-ng-devshell-with-grpc:latest ghcr.io/syslog-ng/dbld-devshell:latest

      - name: Create source tarball
        run: ./dbld/rules pkg-tarball

      - name: Store source tarball as artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-tarball
          path: dbld/build/*.tar.gz

  create-packages:
    needs: create-source-tarball
    uses: ./.github/workflows/create-packages.yml
    with:
      source-tarball-artifact-name: source-tarball
      dbld-image-mode: build
