name: Binary packages

on:
  pull_request:
  push:
  schedule:
    - cron: '00 21 * * *'


jobs:
  tarball:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker image
        run: ./dbld/rules cache-image-tarball

      - name: Tarball
        run: ./dbld/rules pkg-tarball

      - name: Store tarball as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: dbld/build/*.tar.gz

  packages:
    needs: tarball
    uses: ./.github/workflows/create-and-upload-packages.yml
    with:
      tarball_artifact_name: "tarball"
