name: Create release candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'VERSION'
        required: true

jobs:
  create-release-candidate:
    runs-on: ubuntu-18.04
    steps:
      - name: Set ENV variables
        run: |
          echo "::set-env name=RELEASE_VERSION::${{ github.event.inputs.version }}"

      - name: Checkout syslog-ng source
        uses: actions/checkout@v2

      - name: Configure git user
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@github.com"

      - name: Create release candidate git branch
        run: |
          i=0
          while true; do \
            RELEASE_CANDIDATE_BRANCH=v${RELEASE_VERSION}rc${i}; \
            git ls-remote --exit-code --heads origin ${RELEASE_CANDIDATE_BRANCH} || \
              git switch -c ${RELEASE_CANDIDATE_BRANCH} && break; \
            ((i++)); \
          done

      - name: dbld prepare-release
        run: |
          ./dbld/rules prepare-release VERSION=$RELEASE_VERSION

          # TODO: Fix rhel specfile bump!
          sed 's/Version: 3.28.1/Version: $RELEASE_VERSION/g' packaging/rhel/syslog-ng.spec > packaging/rhel/syslog-ng.spec2
          mv packaging/rhel/syslog-ng.spec2 packaging/rhel/syslog-ng.spec

      - name: Commit version bump
        run: |
          git commit -a -s -m "version: bumped to $RELEASE_VERSION"

      - name: Generate NEWS.md
        run: |
          ./news/create-newsfile.py

      - name: Commit NEWS.md
        run: |
          git commit -a -s -m "NEWS: generate for $RELEASE_VERSION"

      # - name: dbld release
      #   run: |
      #     # TODO: Fix this mkdir problem!
      #     rm -rf dbld/build ; mkdir dbld/build

      #     ./dbld/rules release VERSION=$RELEASE_VERSION

      - name: Open Pull Request
        run: |
          git push origin HEAD

