name: Trigger Publish Docker image


on:
  workflow_call:
    # Make sure to select a syslog-ng-* tag


jobs:
  publish-docker-image:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
