name: Upload package to Azure/incoming


on:
  workflow_call:
    inputs:
      pkg-type:
        required: true
        type: string  # stable / nightly
      distros:
        required: false
        type: string
        default: '[
          "debian-stretch",
          "debian-buster",
          "debian-testing",
          "debian-sid",
          "ubuntu-xenial",
          "ubuntu-bionic",
          "debian-bullseye",
          "ubuntu-focal",
          "ubuntu-impish"
        ]'


jobs:
  upload-packages:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'alltilla' # TODO: syslog-ng

    strategy:
      matrix:
        distro: ${{ fromJson(inputs.distros) }}
      fail-fast: false

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package-${{ matrix.distro }}

      - name: Calculate Azure path
        run: |
          if [[ "${{ inputs.pkg-type }}" = "stable" ]]; then
            AZURE_PATH="incoming/release/${{ github.run_id }}/"
          elif [[ "${{ inputs.pkg-type }}" = "nightly" ]]; then
            AZURE_PATH="incoming/nightly/"
          else
            echo Unexpected input: pkg-type=${{ inputs.pkg-type }}
            false
          fi

          echo "AZURE_PATH=${AZURE_PATH}" >> ${GITHUB_ENV}

      # - name: Upload packages to Azure incoming
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az storage blob upload-batch \
      #         --sas-token "${{ secrets.AZURE_SAS_TOKEN }}" \
      #         --account-name "syslogngose" \
      #         --source "${{ matrix.distro }}" \
      #         --destination "${AZURE_PATH}"
